# automatically deploy a new version of a Python package to PyPI whenever a new commit enters the "main" branch and the
# version number has been updated in the "pyproject.toml" file.

name: PyPI Deploy

on:
  push:
    branches: [ main ]
    paths:
      - pyproject.toml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and Deploy
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          python -m twine upload --repository pypi dist/*
